<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice #{{ $invoice->id }} | Weberse</title>
    <style>
        body { font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 0; padding: 24px; background: #f1f5f9; color: #0f172a; }
        .shell { max-width: 720px; margin: 0 auto; background: #ffffff; border-radius: 18px; padding: 24px 28px; box-shadow: 0 18px 40px rgba(15,23,42,0.15); }
        h1 { margin: 0 0 4px; font-size: 24px; }
        .muted { color: #64748b; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; margin-top: 18px; font-size: 14px; }
        th, td { padding: 8px 6px; text-align: left; }
        th { border-bottom: 1px solid #e2e8f0; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; }
        tr:nth-child(even) td { background: #f8fafc; }
        .right { text-align: right; }
        .totals { margin-top: 18px; width: 100%; }
        .totals td { padding: 4px 0; }
        .totals .label { color: #64748b; font-size: 13px; }
        .totals .value { text-align: right; font-weight: 600; }
    </style>
</head>
<body>
    <div class="shell">
        <div>
            <h1>Invoice #{{ $invoice->id }}</h1>
            <div class="muted">
                Issued {{ $invoice->issued_at?->format('d M Y') ?? '-' }}<br>
                Billed to: {{ $invoice->buyer_email }}
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="right">Qty</th>
                    <th class="right">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($invoice->items as $item)
                    <tr>
                        <td>{{ $item->label }}</td>
                        <td class="right">{{ $item->qty }}</td>
                        <td class="right">{{ $invoice->currency }} {{ number_format(($item->line_total_paise ?? 0) / 100, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <table class="totals">
            <tr>
                <td class="label">Subtotal</td>
                <td class="value">{{ $invoice->currency }} {{ number_format(($invoice->subtotal_paise ?? 0) / 100, 2) }}</td>
            </tr>
            <tr>
                <td class="label">Total</td>
                <td class="value">{{ $invoice->currency }} {{ number_format(($invoice->total_paise ?? 0) / 100, 2) }}</td>
            </tr>
            <tr>
                <td class="label">Status</td>
                <td class="value">{{ $invoice->status }}</td>
            </tr>
        </table>

        <p class="muted" style="margin-top: 24px;">
            This invoice was generated by Weberse Store. Keep this file for your records.
        </p>
    </div>
</body>
</html>

