<?php

use App\Http\Controllers\Admin\AnalyticsController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\ClientManagementController;
use App\Http\Controllers\Admin\CrmController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\EmailController;
use App\Http\Controllers\Admin\HrmController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\SupportController;
use Illuminate\Support\Facades\Route;

    Route::middleware(['auth', 'role:admin|hr|sales|support'])->prefix('admin')->name('admin.')->group(function () {
        Route::get('/', DashboardController::class)->name('dashboard');
    Route::get('/cms', [CmsController::class, 'index'])->name('cms.index');
    Route::get('/cms/website-details', [CmsController::class, 'websiteDetails'])->name('cms.website-details');
    Route::patch('/cms/website-details', [CmsController::class, 'updateWebsiteDetails'])->name('cms.website-details.update');
    Route::get('/cms/images', [CmsController::class, 'images'])->name('cms.images');
    Route::patch('/cms/images', [CmsController::class, 'updateImages'])->name('cms.images.update');
    Route::post('/cms/media', [CmsController::class, 'uploadMedia'])->name('cms.media.upload');
    Route::post('/cms/website-details/media', [CmsController::class, 'uploadWebsiteMedia'])->name('cms.website-details.media.upload');
    Route::get('/cms/posts', [CmsController::class, 'posts'])->name('cms.posts.index');
    Route::get('/cms/posts/create', [CmsController::class, 'createPost'])->name('cms.posts.create');
    Route::get('/cms/posts/{post}/edit', [CmsController::class, 'editPost'])->name('cms.posts.edit');
    Route::post('/cms/posts', [CmsController::class, 'storePost'])->name('cms.posts.store');
    Route::patch('/cms/posts/{post}', [CmsController::class, 'updatePost'])->name('cms.posts.update');
    Route::get('/cms/projects', [CmsController::class, 'projects'])->name('cms.projects.index');
    Route::get('/cms/projects/create', [CmsController::class, 'createProject'])->name('cms.projects.create');
    Route::get('/cms/projects/{project}/edit', [CmsController::class, 'editProject'])->name('cms.projects.edit');
    Route::post('/cms/projects', [CmsController::class, 'storeProject'])->name('cms.projects.store');
    Route::patch('/cms/projects/{project}', [CmsController::class, 'updateProject'])->name('cms.projects.update');
    Route::get('/cms/case-studies', [CmsController::class, 'caseStudies'])->name('cms.case-studies.index');
    Route::get('/cms/case-studies/create', [CmsController::class, 'createCaseStudy'])->name('cms.case-studies.create');
    Route::get('/cms/case-studies/{caseStudy}/edit', [CmsController::class, 'editCaseStudy'])->name('cms.case-studies.edit');
    Route::post('/cms/case-studies', [CmsController::class, 'storeCaseStudy'])->name('cms.case-studies.store');
    Route::patch('/cms/case-studies/{caseStudy}', [CmsController::class, 'updateCaseStudy'])->name('cms.case-studies.update');
    Route::get('/cms/testimonials', [CmsController::class, 'testimonials'])->name('cms.testimonials.index');
    Route::post('/cms/testimonials', [CmsController::class, 'storeTestimonial'])->name('cms.testimonials.store');
    Route::patch('/cms/testimonials/{testimonial}', [CmsController::class, 'updateTestimonial'])->name('cms.testimonials.update');
    Route::get('/clients', [ClientManagementController::class, 'index'])->name('clients.index');
    Route::get('/clients/create', [ClientManagementController::class, 'create'])->name('clients.create');
    Route::post('/clients', [ClientManagementController::class, 'store'])->name('clients.store');
    Route::get('/clients/{client}', [ClientManagementController::class, 'show'])->name('clients.show');
    Route::get('/clients/{client}/edit', [ClientManagementController::class, 'edit'])->name('clients.edit');
    Route::patch('/clients/{client}', [ClientManagementController::class, 'update'])->name('clients.update');
    Route::post('/clients/{client}/documents', [ClientManagementController::class, 'storeDocument'])->name('clients.documents.store');
    Route::get('/crm', [CrmController::class, 'index'])->name('crm.index');
    Route::get('/crm/leads', [CrmController::class, 'leads'])->name('crm.leads.index');
    Route::get('/crm/leads/create', [CrmController::class, 'create'])->name('crm.leads.create');
    Route::post('/crm/leads', [CrmController::class, 'store'])->name('crm.leads.store');
    Route::get('/crm/leads/{lead}', [CrmController::class, 'show'])->name('crm.leads.show');
    Route::get('/crm/leads/{lead}/edit', [CrmController::class, 'edit'])->name('crm.leads.edit');
    Route::patch('/crm/leads/{lead}', [CrmController::class, 'update'])->name('crm.leads.update');
    Route::post('/crm/leads/{lead}/notes', [CrmController::class, 'addNote'])->name('crm.leads.notes.store');
    Route::get('/crm/contacts', [CrmController::class, 'contacts'])->name('crm.contacts.index');
    Route::patch('/crm/contacts/{contact}', [CrmController::class, 'updateContact'])->name('crm.contacts.update');
    Route::get('/crm/follow-ups', [CrmController::class, 'followUps'])->name('crm.follow-ups.index');
    Route::post('/crm/follow-ups', [CrmController::class, 'storeFollowUp'])->name('crm.follow-ups.store');
    Route::patch('/crm/follow-ups/{followUp}', [CrmController::class, 'updateFollowUp'])->name('crm.follow-ups.update');
    Route::get('/hrm', [HrmController::class, 'index'])->name('hrm.index');
    Route::get('/hrm/employees', [HrmController::class, 'employees'])->name('hrm.employees.index');
    Route::get('/hrm/jobs', [HrmController::class, 'jobs'])->name('hrm.jobs.index');
    Route::get('/hrm/jobs/create', [HrmController::class, 'createJob'])->name('hrm.jobs.create');
    Route::get('/hrm/jobs/{jobOpening}/edit', [HrmController::class, 'editJob'])->name('hrm.jobs.edit');
    Route::get('/hrm/interviews', [HrmController::class, 'interviews'])->name('hrm.interviews.index');
    Route::get('/hrm/compensation', [HrmController::class, 'compensation'])->name('hrm.compensation.index');
    Route::get('/hrm/expenses', [HrmController::class, 'expenses'])->name('hrm.expenses.index');
    Route::get('/hrm/perks', [HrmController::class, 'perks'])->name('hrm.perks.index');
    Route::get('/hrm/applications', [HrmController::class, 'applications'])->name('hrm.applications.index');
    Route::get('/hrm/applications/{application}', [HrmController::class, 'showApplication'])->name('hrm.applications.show');
    Route::post('/hrm/jobs', [HrmController::class, 'storeJob'])->name('hrm.jobs.store');
    Route::patch('/hrm/jobs/{jobOpening}', [HrmController::class, 'updateJob'])->name('hrm.jobs.update');
    Route::patch('/hrm/applications/{application}', [HrmController::class, 'updateApplication'])->name('hrm.applications.update');
    Route::post('/hrm/interviews', [HrmController::class, 'storeInterview'])->name('hrm.interviews.store');
    Route::patch('/hrm/interviews/{interview}', [HrmController::class, 'updateInterview'])->name('hrm.interviews.update');
    Route::post('/hrm/compensation', [HrmController::class, 'storeCompensation'])->name('hrm.compensation.store');
    Route::patch('/hrm/compensation/{record}', [HrmController::class, 'updateCompensation'])->name('hrm.compensation.update');
    Route::post('/hrm/expenses', [HrmController::class, 'storeExpense'])->name('hrm.expenses.store');
    Route::patch('/hrm/expenses/{claim}', [HrmController::class, 'updateExpense'])->name('hrm.expenses.update');
    Route::post('/hrm/perks', [HrmController::class, 'storePerk'])->name('hrm.perks.store');
    Route::patch('/hrm/perks/{perk}', [HrmController::class, 'updatePerk'])->name('hrm.perks.update');
    Route::get('/support', [SupportController::class, 'index'])->name('support.index');
    Route::patch('/support/{ticket}', [SupportController::class, 'update'])->name('support.update');
    Route::post('/support/{ticket}/reply', [SupportController::class, 'reply'])->name('support.reply');
    Route::get('/analytics', AnalyticsController::class)->name('analytics.index');
    Route::get('/email', [EmailController::class, 'index'])->middleware('role:admin')->name('email.index');
    Route::get('/email/templates', [EmailController::class, 'templates'])->middleware('role:admin')->name('email.templates.index');
    Route::get('/email/templates/create', [EmailController::class, 'createTemplate'])->middleware('role:admin')->name('email.templates.create');
    Route::get('/email/templates/{template}/edit', [EmailController::class, 'editTemplate'])->middleware('role:admin')->name('email.templates.edit');
    Route::post('/email/templates', [EmailController::class, 'storeTemplate'])->middleware('role:admin')->name('email.templates.store');
    Route::patch('/email/templates/{template}', [EmailController::class, 'updateTemplate'])->middleware('role:admin')->name('email.templates.update');
    Route::get('/email/subscribers', [EmailController::class, 'subscribers'])->middleware('role:admin')->name('email.subscribers.index');
    Route::post('/email/subscribers', [EmailController::class, 'storeSubscriber'])->middleware('role:admin')->name('email.subscribers.store');
    Route::patch('/email/subscribers/{subscriber}', [EmailController::class, 'updateSubscriber'])->middleware('role:admin')->name('email.subscribers.update');
    Route::get('/email/campaigns', [EmailController::class, 'campaigns'])->middleware('role:admin')->name('email.campaigns.index');
    Route::get('/email/campaigns/create', [EmailController::class, 'createCampaign'])->middleware('role:admin')->name('email.campaigns.create');
    Route::get('/email/campaigns/{campaign}/edit', [EmailController::class, 'editCampaign'])->middleware('role:admin')->name('email.campaigns.edit');
    Route::post('/email/campaigns', [EmailController::class, 'storeCampaign'])->middleware('role:admin')->name('email.campaigns.store');
    Route::patch('/email/campaigns/{campaign}', [EmailController::class, 'updateCampaign'])->middleware('role:admin')->name('email.campaigns.update');
    Route::post('/email/campaigns/{campaign}/send', [EmailController::class, 'sendCampaign'])->middleware('role:admin')->name('email.campaigns.send');
    Route::get('/email/compose', [EmailController::class, 'composer'])->middleware('role:admin')->name('email.compose');
    Route::post('/email/compose', [EmailController::class, 'sendSingle'])->middleware('role:admin')->name('email.compose.send');
    Route::get('/settings', [SettingsController::class, 'index'])->middleware('role:admin')->name('settings.index');
    Route::patch('/settings/mail', [SettingsController::class, 'updateMail'])->middleware('role:admin')->name('settings.mail.update');
    Route::patch('/settings/hr-mail', [SettingsController::class, 'updateHrMail'])->middleware('role:admin')->name('settings.hr-mail.update');
    Route::patch('/settings/website', [SettingsController::class, 'updateWebsite'])->middleware('role:admin')->name('settings.website.update');
    Route::patch('/settings/integrations', [SettingsController::class, 'updateIntegrations'])->middleware('role:admin')->name('settings.integrations.update');
});
