<?php

return [
    'services' => [
        [
            'slug' => 'mobile-app-development',
            'title' => 'Mobile App Development',
            'icon' => 'smartphone',
            'tagline' => 'Native-feeling apps for ambitious digital products.',
            'summary' => 'Mobile systems engineered for performance, scalability, and clean product execution.',
            'hero' => 'Launch polished mobile experiences with a product team that understands growth, performance, and app-market execution.',
            'image' => '/assets/legacy/app-mockup.png',
            'benefits' => ['Smooth cross-platform delivery', 'Scalable architecture', 'Retention-focused UX'],
            'deliverables' => ['Product flow mapping', 'High-fidelity UI', 'App store launch support', 'Analytics-ready release'],
            'technologies' => ['Flutter', 'React Native', 'Swift', 'Kotlin', 'Firebase'],
            'process' => ['Discovery & product mapping', 'UX wireframes & flows', 'Agile development sprints', 'QA, launch, and iteration'],
            'case_study' => 'Built a service-booking mobile app that simplified user onboarding and reduced booking drop-off.',
        ],
        [
            'slug' => 'web-development',
            'title' => 'Web Development',
            'icon' => 'globe',
            'tagline' => 'Conversion-focused websites and web platforms.',
            'summary' => 'High-performance product sites and platforms with modern frontend architecture and operational clarity.',
            'hero' => 'From premium marketing sites to custom web platforms, Weberse builds digital products that look sharp and work under load.',
            'image' => '/assets/legacy/web-development.png',
            'benefits' => ['Fast loading architecture', 'SEO-friendly pages', 'Flexible CMS-ready builds'],
            'deliverables' => ['Information architecture', 'Component systems', 'CMS integrations', 'Technical SEO foundations'],
            'technologies' => ['Laravel', 'PHP', 'JavaScript', 'TailwindCSS', 'MySQL'],
            'process' => ['Positioning & content planning', 'Design system setup', 'Frontend/backend implementation', 'Optimization & deployment'],
            'case_study' => 'Redesigned an agency site into a structured funnel with improved service clarity and better-qualified leads.',
        ],
        [
            'slug' => 'digital-marketing',
            'title' => 'Digital Marketing',
            'icon' => 'layers',
            'tagline' => 'Clarify the offer, then send the traffic.',
            'summary' => 'Digital campaigns built around clean funnels, sharp messaging, and analytics that show what is actually working.',
            'hero' => 'Weberse combines positioning, landing pages, and channel strategy into one coherent funnel so you are not guessing which campaign moved the needle.',
            'image' => '/assets/legacy/marketing.jpg',
            'benefits' => ['Better qualified leads', 'Clear funnel structure', 'Channel tests without chaos'],
            'deliverables' => ['Landing page assets', 'Campaign setup', 'Tracking dashboards', 'Offer messaging review'],
            'technologies' => ['Meta & Google Ads', 'Analytics', 'Landing Pages', 'Funnels'],
            'process' => ['Offer & audience mapping', 'Funnel and tracking setup', 'Campaign launch', 'Iteration based on data'],
            'case_study' => 'Structured a simple 3-step funnel for a services brand that reduced unqualified inquiries while increasing total leads.',
        ],
        [
            'slug' => 'ui-ux-design',
            'title' => 'UI/UX Design',
            'icon' => 'palette',
            'tagline' => 'Interfaces that feel clear, premium, and product-ready.',
            'summary' => 'Design systems and high-clarity interfaces shaped for trust, adoption, and conversion.',
            'hero' => 'We turn complex offerings into sharp interfaces with strong hierarchy, modern layout systems, and user-centered flows.',
            'image' => '/assets/legacy/uiux-design.jpg',
            'benefits' => ['Better information hierarchy', 'Faster user onboarding', 'Consistent visual systems'],
            'deliverables' => ['Wireframes and journeys', 'UI system libraries', 'Responsive prototypes', 'Developer-ready design specs'],
            'technologies' => ['Figma', 'Design Tokens', 'Prototyping', 'Usability Reviews'],
            'process' => ['Research & positioning', 'Wireframes', 'High-fidelity UI', 'Design QA with engineering'],
            'case_study' => 'Created a dashboard system that reduced UI clutter while improving feature discoverability.',
        ],
        [
            'slug' => 'ai-automation',
            'title' => 'AI Automation',
            'icon' => 'sparkles',
            'tagline' => 'Practical intelligence embedded into operations.',
            'summary' => 'AI integrations for support, knowledge workflows, automation layers, and intelligent internal tooling.',
            'hero' => 'Weberse applies AI where it creates operational leverage, not where it creates noise.',
            'image' => '/assets/images/service-showcase.svg',
            'benefits' => ['Reduced manual repetition', 'Faster response times', 'Cleaner internal processes'],
            'deliverables' => ['Use-case audit', 'Prompt workflows', 'Human review guardrails', 'Internal AI interfaces'],
            'technologies' => ['OpenAI APIs', 'Workflow Services', 'Prompt Systems', 'Webhook Integrations'],
            'process' => ['Workflow audit', 'Use-case prioritization', 'Prototype & validate', 'Ship guarded automations'],
            'case_study' => 'Implemented AI-assisted response workflows for customer operations with human approval layers.',
        ],
        [
            'slug' => 'whatsapp-cloud-automation',
            'title' => 'WhatsApp Cloud & Automation',
            'icon' => 'bot',
            'tagline' => 'Make WhatsApp behave like part of your system, not a separate app.',
            'summary' => 'WhatsApp Cloud API integrations for lead capture, support flows, notifications, and light-weight automations tied to your CRM or platform.',
            'hero' => 'Weberse wires WhatsApp into your existing stack so conversations, triggers, and updates live inside your systems instead of scattered devices.',
            'image' => '/assets/legacy/whatsapp-cloud.png',
            'benefits' => ['Centralised conversations', 'Automated notifications', 'Programmable flows'],
            'deliverables' => ['Template setup', 'Webhook handling', 'Operational dashboards', 'Message flow logic'],
            'technologies' => ['WhatsApp Cloud API', 'Webhooks', 'Internal Dashboards', 'CRMs'],
            'process' => ['Conversation mapping', 'Flow and template design', 'API integration', 'Monitoring and refinement'],
            'case_study' => 'Connected WhatsApp Cloud to a lead intake system so new prospects, updates, and internal alerts stayed in sync without manual forwarding.',
        ],
        [
            'slug' => 'email-marketing-automation',
            'title' => 'Email Marketing & Automation',
            'icon' => 'mail',
            'tagline' => 'Email sequences that match how your buyers actually decide.',
            'summary' => 'Lifecycle emails, newsletters, and transactional sequences configured around your funnel, not just a generic list blast.',
            'hero' => 'Weberse designs and implements email systems that combine good copy, sensible segmentation, and reliable delivery infrastructure.',
            'image' => '/assets/legacy/email-marketing.jpg',
            'benefits' => ['Better follow-up', 'Cleaner segmentation', 'More predictable revenue from email'],
            'deliverables' => ['Lifecycle sequences', 'Template design', 'Segmentation logic', 'Deliverability setup'],
            'technologies' => ['SMTP & API Providers', 'Marketing Platforms', 'Segmented Lists'],
            'process' => ['Lifecycle and content mapping', 'Template and system setup', 'Automation rules', 'Ongoing tuning'],
            'case_study' => 'Built a segmented email system for a services brand that turned one-off inquiries into a nurtured pipeline.',
        ],
        [
            'slug' => 'startup-mvp-development',
            'title' => 'Startup MVP Development',
            'icon' => 'rocket',
            'tagline' => 'Ship the first version without shipping chaos.',
            'summary' => 'MVP systems built for validation speed, disciplined scope, and future technical leverage.',
            'hero' => 'We scope MVPs around the actual user journey and the smallest valuable feature set, then build for learning velocity.',
            'image' => '/assets/legacy/office-meeting.jpg',
            'benefits' => ['Lean scope control', 'Founder-friendly iteration', 'Future-ready architecture'],
            'deliverables' => ['Founder scoping workshops', 'Admin and client roles', 'Core journey delivery', 'Launch analytics'],
            'technologies' => ['Laravel', 'JavaScript', 'APIs', 'Stripe/WHMCS Integrations', 'Cloud Deployment'],
            'process' => ['Product scoping', 'Experience design', 'Focused build', 'Launch and feedback loop'],
            'case_study' => 'Delivered a founder-led MVP with admin operations, client access, and clear analytics from day one.',
        ],
        [
            'slug' => 'custom-software-development',
            'title' => 'Custom Software Development',
            'icon' => 'cpu',
            'tagline' => 'Internal systems built around how your business actually works.',
            'summary' => 'Scalable systems, cloud-ready software, and internal platforms tailored to real operational workflows.',
            'hero' => 'We build structured internal platforms that replace fragmented tools and create better visibility across teams.',
            'image' => '/assets/legacy/software.png',
            'benefits' => ['Unified workflows', 'Role-based access', 'Long-term maintainability'],
            'deliverables' => ['System mapping', 'Role-based dashboards', 'Integration planning', 'Support-ready modules'],
            'technologies' => ['Laravel', 'REST APIs', 'Redis', 'Queue Workers', 'S3-Compatible Storage'],
            'process' => ['System mapping', 'Module planning', 'Incremental delivery', 'Support and extension'],
            'case_study' => 'Consolidated website, support, and client operations into one controlled business platform.',
        ],
    ],
    'projects' => [
        [
            'slug' => 'zenflow-ops',
            'title' => 'Zenflow Ops',
            'category' => 'Operations Platform',
            'description' => 'A unified business operations dashboard for lead intake, support, and client collaboration.',
            'stack' => ['Laravel', 'TailwindCSS', 'Redis'],
            'image' => '/assets/legacy/work-1.jpg',
            'challenge' => 'The team was managing client conversations, leads, and delivery updates across disconnected tools.',
            'solution' => 'We designed a single operations platform with role-based dashboards, cleaner intake, and structured collaboration views.',
            'outcome' => 'The business gained one operational source of truth, faster follow-up, and better visibility for both staff and clients.',
            'metrics' => ['3 core workflows unified', 'Single dashboard for staff', 'Faster client response cycle'],
        ],
        [
            'slug' => 'nova-host',
            'title' => 'Nova Host',
            'category' => 'Hosting Experience',
            'description' => 'A premium hosting storefront and onboarding experience layered on top of WHMCS.',
            'stack' => ['WHMCS', 'Blade', 'JavaScript'],
            'image' => '/assets/legacy/work-2.jpg',
            'challenge' => 'The product catalog and billing flow felt generic, which made differentiation difficult in a crowded market.',
            'solution' => 'We redesigned the marketing and hosting journey around clearer plan positioning and a stronger handoff into WHMCS.',
            'outcome' => 'The storefront looked more premium, communicated value faster, and made hosting offers easier to compare.',
            'metrics' => ['Sharper plan differentiation', 'Branded WHMCS handoff', 'Cleaner product navigation'],
        ],
        [
            'slug' => 'pulse-mobile',
            'title' => 'Pulse Mobile',
            'category' => 'Mobile Product',
            'description' => 'A service-booking mobile application with a clean acquisition and retention flow.',
            'stack' => ['Flutter', 'Firebase', 'Figma'],
            'image' => '/assets/legacy/work-3.jpg',
            'challenge' => 'The booking journey needed to feel simple for users while still supporting operational visibility on the backend.',
            'solution' => 'We mapped a lighter onboarding flow, designed clear UI states, and paired the mobile experience with operational support tools.',
            'outcome' => 'The result was a smoother product experience with better booking flow clarity and stronger product trust.',
            'metrics' => ['Reduced booking friction', 'Mobile-first UI system', 'Operational visibility built in'],
        ],
    ],
    'case_studies' => [
        [
            'slug' => 'scaling-a-modern-hosting-brand',
            'title' => 'Scaling a Modern Hosting Brand',
            'summary' => 'How a fragmented hosting offer was restructured into a cleaner branded funnel.',
            'client' => 'CloudHarbor Hosting',
            'duration' => '8 weeks',
            'engagement' => 'Website redesign + hosting funnel',
            'challenge' => 'Low trust, weak differentiation, and multiple disconnected purchase paths.',
            'solution' => 'Introduced a focused marketing site, service positioning, and a branded handoff to WHMCS.',
            'outcome' => 'The hosting offer became easier to understand, the brand looked more credible, and the billing journey felt consistent from first click to checkout.',
            'results' => ['Clearer service navigation', 'Higher trust visual language', 'Better handoff into checkout'],
            'industry' => 'Hosting',
            'image' => '/assets/legacy/work-2.jpg',
            'services' => ['Web Development', 'UI/UX Design', 'WHMCS Integration'],
            'stack' => ['Laravel', 'Blade', 'TailwindCSS', 'WHMCS'],
            'metrics' => ['Stronger buyer trust', 'Cleaner hosting plans', 'More coherent billing journey'],
            'quote' => 'The commercial story finally felt clear. Prospects understood the plans faster and the transition into billing no longer felt like a separate product.',
            'quote_author' => 'Operations Lead',
        ],
        [
            'slug' => 'building-an-internal-ops-platform',
            'title' => 'Building an Internal Ops Platform',
            'summary' => 'Replacing scattered tools with a modular system for leads, hiring, and support.',
            'client' => 'Vertex Commerce',
            'duration' => '12 weeks',
            'engagement' => 'Internal platform build',
            'challenge' => 'The team lacked one controlled view of business operations.',
            'solution' => 'Designed a modular Laravel platform with CMS, CRM, HRM, support, and portal workflows.',
            'outcome' => 'The business moved from disconnected tools into a single operating surface with clearer ownership, cleaner data flow, and better visibility for staff and clients.',
            'results' => ['Fewer disconnected processes', 'Better role visibility', 'Cleaner client experience'],
            'industry' => 'Operations',
            'image' => '/assets/legacy/software.png',
            'services' => ['Custom Software Development', 'CRM', 'Client Portal'],
            'stack' => ['Laravel', 'Alpine.js', 'PostgreSQL', 'Redis'],
            'metrics' => ['Unified internal views', 'Role-based visibility', 'Less tool fragmentation'],
            'quote' => 'Instead of juggling disconnected tools, the team now works from one structured workspace. That improved internal speed almost immediately.',
            'quote_author' => 'Founder',
        ],
    ],
    'testimonials' => [
        [
            'name' => 'Amit Verma',
            'company' => 'Vertex Commerce',
            'quote' => 'Weberse brought our website, lead intake, and client support into one disciplined platform.',
        ],
        [
            'name' => 'Nisha Kapoor',
            'company' => 'CloudHarbor',
            'quote' => 'Their team translated a vague platform idea into a production-ready system with clear delivery checkpoints.',
        ],
        [
            'name' => 'Rahul Sethi',
            'company' => 'Fino Finance',
            'quote' => 'The interface quality improved trust immediately, and the engineering underneath was structured enough for long-term scale.',
        ],
        [
            'name' => 'Daniel Brooks',
            'company' => 'Northlane Digital',
            'quote' => 'We needed a sharper B2B presence and better operational tooling. Weberse delivered both without overcomplicating the stack.',
        ],
        [
            'name' => 'Sara Iqbal',
            'company' => 'MedAxis',
            'quote' => 'Their process was direct, technically sound, and unusually clear. That made the project easier to manage from day one.',
        ],
    ],
    'industries' => [
        ['label' => 'SaaS', 'icon' => 'layers'],
        ['label' => 'Hosting', 'icon' => 'server'],
        ['label' => 'Professional Services', 'icon' => 'briefcase'],
        ['label' => 'Ecommerce', 'icon' => 'shopping-cart'],
        ['label' => 'Healthcare', 'icon' => 'heart-pulse'],
        ['label' => 'Education', 'icon' => 'graduation-cap'],
        ['label' => 'Fintech', 'icon' => 'landmark'],
        ['label' => 'Logistics', 'icon' => 'truck'],
        ['label' => 'Real Estate', 'icon' => 'building'],
        ['label' => 'Travel', 'icon' => 'plane'],
        ['label' => 'Hospitality', 'icon' => 'hotel'],
        ['label' => 'Manufacturing', 'icon' => 'factory'],
    ],
    'technologies' => ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Rust', 'Go', 'PostgreSQL', 'Redis', 'AWS', 'Terraform', 'Kubernetes', 'OpenAI API'],
    'tech_stack' => [
        [
            'category' => 'Frontend',
            'summary' => 'High-performance interfaces with modern DX and strong delivery velocity.',
            'items' => [
                ['label' => 'Next.js 15', 'meta' => 'Server Actions', 'icon' => 'nextdotjs'],
                ['label' => 'TypeScript', 'meta' => 'Strict Safety', 'icon' => 'typescript'],
                ['label' => 'Tailwind CSS', 'meta' => 'Design System', 'icon' => 'tailwindcss'],
                ['label' => 'Framer Motion', 'meta' => 'Premium Motion', 'icon' => 'framer'],
            ],
        ],
        [
            'category' => 'Backend',
            'summary' => 'Memory-safe and throughput-focused services for serious production workloads.',
            'items' => [
                ['label' => 'Rust', 'meta' => 'Actix Services', 'icon' => 'rust'],
                ['label' => 'Go', 'meta' => 'High-Concurrency', 'icon' => 'go'],
                ['label' => 'PostgreSQL', 'meta' => 'Edge Data', 'icon' => 'postgresql'],
                ['label' => 'Redis', 'meta' => 'Queue + Cache', 'icon' => 'redis'],
            ],
        ],
        [
            'category' => 'Cloud',
            'summary' => 'Cloud-native delivery with reproducible infrastructure and controlled deployments.',
            'items' => [
                ['label' => 'AWS', 'meta' => 'Cloud Platform', 'icon' => 'aws-fallback'],
                ['label' => 'Terraform', 'meta' => 'Infra as Code', 'icon' => 'aws-fallback'],
                ['label' => 'Kubernetes', 'meta' => 'Orchestration', 'icon' => 'kubernetes'],
                ['label' => 'Vercel', 'meta' => 'Frontend Edge', 'icon' => 'vercel'],
            ],
        ],
        [
            'category' => 'AI / ML',
            'summary' => 'Production-oriented AI integrations with guarded workflows and useful automation.',
            'items' => [
                ['label' => 'PyTorch', 'meta' => 'Model Layer', 'icon' => 'pytorch'],
                ['label' => 'OpenAI API', 'meta' => 'Inference', 'icon' => 'openai-fallback'],
                ['label' => 'LangChain', 'meta' => 'Agent Orchestration', 'icon' => 'langchain'],
                ['label' => 'Retrieval', 'meta' => 'Knowledge Flows', 'icon' => 'database-fallback'],
            ],
        ],
    ],
];
